apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-config
  namespace: {{ .Namespace }}
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "{{ .Name }}"
  DB_USER: "{{ .Name }}"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"