apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-monitoring
  namespace: {{ .Namespace }}
spec:
  selector:
    app: {{ .Name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}-monitor
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Name }}
  endpoints:
    - port: metrics
      interval: 30s